-- Snowflake user creation
-- Step 1: Use an admin role
USE ROLE ACCOUNTADMIN;

-- Step 2: Create the MOVIELENS_ROLE and assign it to ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS movielens_role;
GRANT ROLE movielens_role TO USER <SNOWFLAKE_USERNAME>;

-- Step 3: Create a default warehouse
CREATE WAREHOUSE IF NOT EXISTS movielens_wh WITH warehouse_size='x-small'; 
GRANT USAGE ON WAREHOUSE movielens_wh TO ROLE movielens_role;

-- Step 4: Create the `dbt` user and assign to the MOVIELENS_ROLE
CREATE USER IF NOT EXISTS dbt
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='MOVIELENS_WH'
  DEFAULT_ROLE=MOVIELENS_ROLE
  DEFAULT_NAMESPACE='MOVIELENS.RAW'
  COMMENT='DBT user used for data transformation';
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE MOVIELENS_ROLE TO USER dbt;

-- Step 5: Create a database and schema for the MovieLens project
CREATE DATABASE IF NOT EXISTS MOVIELENS;
CREATE SCHEMA IF NOT EXISTS MOVIELENS.RAW;

-- Step 6: Grant permissions to the `MOVIELENS_ROLE` 
GRANT ALL ON WAREHOUSE MOVIELENS_WH TO ROLE MOVIELENS_ROLE;
GRANT ALL ON DATABASE MOVIELENS TO ROLE MOVIELENS_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE MOVIELENS TO ROLE MOVIELENS_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE MOVIELENS TO ROLE MOVIELENS_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA MOVIELENS.RAW TO ROLE MOVIELENS_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA MOVIELENS.RAW TO ROLE MOVIELENS_ROLE;
